# Generated by Django 4.2.7 on 2024-02-01 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
